//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.RegularExpressions;
using System.Xml.Serialization;

namespace OfficeDevPnP.Core.Tests.Utilities
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009", IsNullable = false)]
    public partial class Query
    {

        private Property[] propertiesField;

        private Query[] query1Field;

        private string selectAllPropertiesField;

        private string idField;

        private string objectPathIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", typeof(Property), IsNullable = false)]
        public Property[] Properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Query")]
        public Query[] Query1
        {
            get
            {
                return this.query1Field;
            }
            set
            {
                this.query1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SelectAllProperties
        {
            get
            {
                return this.selectAllPropertiesField;
            }
            set
            {
                this.selectAllPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = Regex.Replace(value, "[0-9]", "");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectPathId
        {
            get
            {
                return this.objectPathIdField;
            }
            set
            {
                this.objectPathIdField = Regex.Replace(value, "[0-9]", "");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009", IsNullable = false)]
    public partial class Property
    {

        private string nameField;

        private string scalarPropertyField;

        private string idField;

        private string parentIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ScalarProperty
        {
            get
            {
                return this.scalarPropertyField;
            }
            set
            {
                this.scalarPropertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = Regex.Replace(value, "[0-9]", "");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = Regex.Replace(value, "[0-9]", "");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009", IsNullable = false)]
    public partial class Request
    {

        private RequestActions[] actionsField;

        private RequestObjectPaths[] objectPathsField;

        private string addExpandoFieldTypeSuffixField;

        private string schemaVersionField;

        private string libraryVersionField;

        private string applicationNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Actions")]
        public RequestActions[] Actions
        {
            get
            {
                return this.actionsField;
            }
            set
            {
                this.actionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectPaths")]
        public RequestObjectPaths[] ObjectPaths
        {
            get
            {
                return this.objectPathsField;
            }
            set
            {
                this.objectPathsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AddExpandoFieldTypeSuffix
        {
            get
            {
                return this.addExpandoFieldTypeSuffixField;
            }
            set
            {
                this.addExpandoFieldTypeSuffixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LibraryVersion
        {
            get
            {
                return this.libraryVersionField;
            }
            set
            {
                this.libraryVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.applicationNameField;
            }
            set
            {
                this.applicationNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    public partial class RequestActions
    {

        private RequestActionsObjectPath[] objectPathField;

        private Query[] queryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectPath")]
        public RequestActionsObjectPath[] ObjectPath
        {
            get
            {
                return this.objectPathField;
            }
            set
            {
                this.objectPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Query")]
        public Query[] Query
        {
            get
            {
                return this.queryField;
            }
            set
            {
                this.queryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    public partial class RequestActionsObjectPath
    {

        private string idField;

        private string objectPathIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = Regex.Replace(value, "[0-9]", "");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectPathId
        {
            get
            {
                return this.objectPathIdField;
            }
            set
            {
                this.objectPathIdField = Regex.Replace(value, "[0-9]", "");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    public partial class RequestObjectPaths
    {

        private RequestObjectPathsStaticProperty[] staticPropertyField;

        private Property[] propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StaticProperty")]
        public RequestObjectPathsStaticProperty[] StaticProperty
        {
            get
            {
                return this.staticPropertyField;
            }
            set
            {
                this.staticPropertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public Property[] Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    public partial class RequestObjectPathsStaticProperty
    {

        private string idField;

        private string typeIdField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = Regex.Replace(value, "[0-9]", "");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeId
        {
            get
            {
                return this.typeIdField;
            }
            set
            {
                this.typeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/clientquery/2009", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(Property))]
        [System.Xml.Serialization.XmlElementAttribute("Query", typeof(Query))]
        [System.Xml.Serialization.XmlElementAttribute("Request", typeof(Request))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// And public Property[][] Properties changed to Property[] by mr Patrik
// 